### ISSUE TITLE
Please provide an example (node.js) 

### ISSUE THREAD

**Issue by Artysteel** [wireapp/wire-webapp-core#14]
Could you please provide an example to send message/call/video call from one user to another using this CORE. (both users are friends)

**Comment by bennyn** [comment]
Hallo @Artysteel, it's nice to see your interest in our "core" module. 

Unfortunately, only the sending of text messages is offered so far.

Here is a sample how you could write your own Wire CLI for Node.js:

```javascript
const cryptobox = require('wire-webapp-cryptobox');
const stdin = process.openStdin();
const wire = require('wire-webapp-core');

const amountOfPreKeys = 4;
const storage = new cryptobox.store.Cache();
const box = new cryptobox.Cryptobox(storage, amountOfPreKeys);

const credentials = {email: 'name@email.com', password: 'secret'};
const user = new wire.User(credentials, box);

user.login(true)
.then((service) => {
  const conversationId = '7f0939c8-dbd9-48f5-839e-b0ebcfffec8c';
  stdin.addListener('data', (data) => {
    service.conversation.sendTextMessage(conversationId, data.toString().trim());
  });
})
.catch((error) => {
  console.log(`Error: ${error.message} (${error.stack})`);
  process.exit(1);
});
```

**Comment by Artysteel** [comment]
Thanks for example!

What conversation ID stands for? Which one should I use/where to find it? (if I send message from one user to another)

What is the correct way to store keys? each time I launch this script, it generates key (I am using my own account) and it each time says - that it was used on a new device(node.js) and I need to verify each time

**Comment by bennyn** [comment]
> What conversation ID stands for? Which one should I use/where to find it?

The conversation ID is the unique identifier for each conversation (one-to-one conversations & group conversations). There are two ways how you can get it.

**1. via "Inspect Element"**

1. Login on https://app.wire.com/
1. Inspect a conversation name from the conversation list
1. Conversation ID will be the value of the `data-uie-uid` attribute

![untitled](https://cloud.githubusercontent.com/assets/469989/24613145/b46a6372-1887-11e7-8059-f3365790b3bc.png)

**2. via "JavaScript Console"**

1. Login on https://app.wire.com/
1. Select a conversation
1. Execute `wire.app.repository.conversation.active_conversation().id` within the [Chrome DevTools JavaScript Console](https://developers.google.com/web/tools/chrome-devtools/console/)

> What is the correct way to store keys?

We store keys within a [Cryptobox Store](https://github.com/wireapp/wire-webapp-cryptobox). At the moment there are 2 different [store implementations](https://github.com/wireapp/wire-webapp-cryptobox/tree/v5.0.1/src/main/ts/store):

- Cache
- IndexedDB

Because Node.js does not have IndexedDB support, you can only use the Cache store, which is not persistent and creates a new Cryptobox on each run but we are working on a File store for Node.js which will be available soon: https://github.com/wireapp/wire-webapp-cryptobox/tree/file-store

**Comment by bennyn** [comment]
I'm considering this as answered, but feel free to ask follow-up questions if you like. 😃
